#!/bin/bash

cd /tmp/rom

. build/envsetup.sh
lunch xdroid_X01BD-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 32G
ccache -o compression=true
ccache -z

make xd -j8 &
sleep 95m
kill %1
ccache -s

#make xd -j8
